name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pygame

    - name: Compile Python script and move assets
      run: |
        python Main.py

        mkdir -p Assets
        mv Assets/* Assets/

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompiledFiles
        path: Assets/
