name: Build (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pygame pyinstaller

    - name: Compile Python script and move assets
      run: |
        pyinstaller Main.py --add-data "/home/runner/work/Manananggal-Fly/Manananggal-Fly/Assets;Assets" --noconsole --name "Manananggal Flight" --icon "/home/runner/work/Manananggal-Fly/Manananggal-Fly/Assets/icon.png"
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CompiledFiles
        path: dist/
